/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class anjelloatoz_blippAR_BlippTesterActivity */

#ifndef _Included_anjelloatoz_blippAR_BlippTesterActivity
#define _Included_anjelloatoz_blippAR_BlippTesterActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     anjelloatoz_blippAR_BlippTesterActivity
 * Method:    invokeFirstNativeFunction
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_anjelloatoz_blippAR_BlippTesterActivity_invokeFirstNativeFunction
  (JNIEnv *, jobject);

/*
 * Class:     anjelloatoz_blippAR_BlippTesterActivity
 * Method:    invokeSecondNativeFunction
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_anjelloatoz_blippAR_BlippTesterActivity_invokeSecondNativeFunction
  (JNIEnv *, jobject);

/*
 * Class:     anjelloatoz_blippAR_BlippTesterActivity
 * Method:    invokeThirdNativeFunction
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_anjelloatoz_blippAR_BlippTesterActivity_invokeThirdNativeFunction
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
